### ISSUE TITLE
What's the nest thing to implement? 

### ISSUE THREAD

**Issue by dazza5000** [jmcmillenmusic/js-card-game-war#7]
Looking good so far

**Comment by jmcmillenmusic** [comment]
Thank you so much!
The next things are to make sure that the `take()` and `give()` functions work as intended on both the back end and front end.

**Comment by jmcmillenmusic** [comment]
Effectively, I think at this point, it's finished.  I'm open to any and all suggestions and feedback if you have any.

**Comment by dazza5000** [comment]
I pressed shuffle and deal and nothing happened. What do I need to do to play?

**Comment by jmcmillenmusic** [comment]
Hi, Darran!
It's working fine on my end.  I'm pretty sure that I need to publish this so people can see it.
I'll have that done tonight or tomorrow.

**Comment by jmcmillenmusic** [comment]
Hi, Darran!
It's now deployed at this link: https://jmcmillenmusic.github.io/js-card-game-war/
Please let me know if it works for you.  If not, can you send me a video/screenshot of what's going on, please?

**Comment by dazza5000** [comment]
Works great and it looks like it is mobile responsive. Was able to successfully play on my phone :)

**Comment by jmcmillenmusic** [comment]
Great!  Thanks for checking it out!  I greatly appreciate it.
